# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='user',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 2, 12, 15, 11, 59, 171858, tzinfo=utc)),
        ),
    ]
