# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0002_auto_20170212_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
