# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0003_auto_20170212_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='debit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
