# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0006_auto_20170213_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_id',
            new_name='ref_transaction_id',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 13, 11, 56, 24, 824558, tzinfo=utc)),
        ),
    ]
