# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0008_remove_transactions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='date',
        ),
        migrations.AlterField(
            model_name='transfers',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
