# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0009_auto_20170213_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transfers',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
