# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0011_transactions_destination_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='settelment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='settelment_currency',
            field=models.TextField(null=True),
        ),
    ]
