# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0012_auto_20170213_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='teest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('test', models.CharField(max_length=10)),
            ],
        ),
    ]
