# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0013_teest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='billing_currency',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='destination_country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_currency',
            field=models.TextField(null=True),
        ),
    ]
