# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0014_auto_20170214_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teest',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='source',
        ),
        migrations.AddField(
            model_name='transactions',
            name='card_id',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
